### ISSUE TITLE
【提案段階】用語集ページを作る

### ISSUE THREAD

**Issue by sudame** [CoinsOpenCampus2017/ocpt17-computer#29]
資料に存外プログラミング用語が転がっていたので、用語集ページを作るのはいかがでしょう

**Comment by HajimeONO** [comment]
そうしましょう。どのあたり作るか決めたら作ります

**Comment by sudame** [comment]
どのあたりっていうのは、どの用語を解説するかってことですか？

**Comment by HajimeONO** [comment]
それもそうだけど、サイトのどの位置に作るかを決めたい。準備のとこに作っていいのかな？それともそのとなりに新しいstep生やすのがいいのかな？それ以外？

**Comment by sudame** [comment]
Q&Aと同じ扱いで独立させてはどうでしょう
左カラム的には、

[はじめに, 体験, 発展]
[Q&A]
[用語集]

となるような構成に

**Comment by HajimeONO** [comment]
とりあえずそれで
