### ISSUE TITLE
Create 用語集

### ISSUE THREAD

**Issue by HajimeONO** [CoinsOpenCampus2017/ocpt17-computer#30]
Q&Aの兄弟のとして生やす

**Comment by sudame** [comment]
https://github.com/CoinsOpenCampus2017/ocpt17-computer/wiki/%E7%94%A8%E8%AA%9E%E9%9B%86%E3%81%AB%E6%9B%B8%E3%81%8F%E9%A0%85%E7%9B%AE%E3%82%92%E6%8A%95%E3%81%92%E3%82%8B%E3%83%9A%E3%83%BC%E3%82%B8

作るべき項目投げるWikiページ作りました
