### ISSUE TITLE
ヘッダーの大学ロゴがずれている

### ISSUE THREAD

**Issue by HajimeONO** [CoinsOpenCampus2017/ocpt17-computer#32]
初期のころと比べてロゴが上方向にずれているように見えます。
おそらく画像の設定とかをいじった影響だと思います。
たいした問題ではない気もしますが、手が空いてたら直してください。

**Comment by sudame** [comment]
修正しておきます

**Comment by sudame** [comment]
[#33](https://github.com/CoinsOpenCampus2017/ocpt17-computer/pull/33)

修正しましたのでご確認ください
