### ISSUE TITLE
「体験」の構成を資料に合わせる

### ISSUE THREAD

**Issue by HajimeONO** [CoinsOpenCampus2017/ocpt17-computer#5]
おそらく資料を作ってた方とこっちのほうで構成のイメージが結構違ったみたいなのでbranch切って新構成案を出しましょう

**Comment by sudame** [comment]
sudame-dev ブランチを切りましたので、今から調整してみます

**Comment by HajimeONO** [comment]
コンテンツはこっちも手伝うので形ができたらpushしてください

**Comment by sudame** [comment]
「準備」を「はじめに」に移し、来栖さんの資料で「発展」と付いているものは「もっと体験」に掲載する方針にしました。
ページ構成を確認しつつコンテンツ入れをやっていただけるとありがたいです。
分担どうしましょうか。

**Comment by HajimeONO** [comment]
とりあえずページごとにissue立てて半々くらいでassignしましょう

**Comment by HajimeONO** [comment]
よおこそはいっそのことサイドバーでいい気がしてきた

**Comment by sudame** [comment]
なるほど
サイドバー、全ページの目次みたいなの入れようと思うんですが(issue立てます)

**Comment by HajimeONO** [comment]
いいと思います。サイドバーいじったら一旦マスターにマージして、そっからおのおのbranch切ってコンテンツ作りましょう。
